name: Solicitar nueva característica ✨
description: Sugiere o propone una nueva funcionalidad para mejorar CertUs Marketplace.
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ¡Gracias por tu interés en mejorar CertUs! Por favor, completa las siguientes secciones para describir la nueva característica que propones.

  - type: textarea
    id: descripcion
    attributes:
      label: "Descripción de la característica"
      placeholder: "Un botón en la pantalla X que permita hacer Y"
    validations:
      required: true

  - type: textarea
    id: motivacion
    attributes:
      label: "¿Por qué debería implementarse?"
      placeholder: "Permitirá hacer Y, lo cual es necesario para Z"

  - type: textarea
    id: contexto
    attributes:
      label: "Contexto adicional"
      placeholder: "Agrega cualquier otro contexto, ejemplos o capturas de pantalla que ayuden a entender mejor la propuesta."

  - type: dropdown
    id: asignacion
    attributes:
      label: "¿Te gustaría trabajar en esta propuesta?"
      options:
        - "Sí, me gustaría ayudar."
        - "No, solo propongo la idea."

  - type: markdown
    attributes:
      value: |
        ¡Gracias por tu sugerencia! Evaluaremos su viabilidad y utilidad junto al equipo de CertUs.
